services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - file-share-network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8081:80" # Changed host port to 8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - file-share-network
    restart: always

networks:
  file-share-network:
    driver: bridge
